server:
  port: ${PORT:8103}

endpoints:
  health:
    sensitive: false
  shutdown:
    enabled: true

spring:
  cloud:
    config:
      server:
        git:
          uri: ${conf:https://github.com/emerzse/configTutorial}